Q3- Compare Neural Network and SVM in Classification of heart disease data set in R or Python
language.

To answer this question we have used Python language. First we compared different kernel for SVM and then we compared Stochastic Gradient Descent and Adamn for ANN. Finally compared ANN and SVM.

In [17]:
# Import the Libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [8]:
heart = pd.read_csv("heart.csv")

X = heart.drop(columns=["target"])
y = heart["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [3]:
# Linear kernel
svc_linear = svm.SVC(kernel="linear")
svc_linear.fit(X_train, y_train)
y_pred=svc_linear.predict(X_test)
linear_acc = svc_linear.score(X_test, y_test)
print("Linear kernel accuracy:", linear_acc)
print("Confusion matrix")
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Linear kernel accuracy: 0.8048780487804879
Confusion matrix
[[72 30]
 [10 93]]
              precision    recall  f1-score   support

           0       0.88      0.71      0.78       102
           1       0.76      0.90      0.82       103

    accuracy                           0.80       205
   macro avg       0.82      0.80      0.80       205
weighted avg       0.82      0.80      0.80       205



In [7]:
# Gaussian kernel
rbf_svc = svm.SVC(kernel='rbf')
rbf_svc.fit(X_train, y_train)
y_pred=rbf_svc.predict(X_test)
rbf_svc_acc = rbf_svc.score(X_test, y_test)
print(f"Gaussian kernel accuracy: {rbf_svc_acc}")
print("Confusion matrix")
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Gaussian kernel accuracy: 0.6829268292682927
Confusion matrix
[[62 40]
 [25 78]]
              precision    recall  f1-score   support

           0       0.71      0.61      0.66       102
           1       0.66      0.76      0.71       103

    accuracy                           0.68       205
   macro avg       0.69      0.68      0.68       205
weighted avg       0.69      0.68      0.68       205



In [9]:
# Sigmoid kernel
sigmoid_svc = svm.SVC(kernel='sigmoid')
sigmoid_svc.fit(X_train, y_train)
y_pred=sigmoid_svc.predict(X_test)
sigmoid_svc_acc = sigmoid_svc.score(X_test, y_test)
print(f"Sigmoid kernel accuracy: {sigmoid_svc_acc}")
print("Confusion matrix")
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Sigmoid kernel accuracy: 0.4926829268292683
Confusion matrix
[[47 55]
 [49 54]]
              precision    recall  f1-score   support

           0       0.49      0.46      0.47       102
           1       0.50      0.52      0.51       103

    accuracy                           0.49       205
   macro avg       0.49      0.49      0.49       205
weighted avg       0.49      0.49      0.49       205



In [12]:
#pip install tensorflow


     -------------------------------------- 266.3/266.3 MB 9.3 MB/s eta 0:00:00
  Using cached tensorboard-2.11.2-py3-none-any.whl (6.0 MB)
  Using cached libclang-15.0.6.1-py2.py3-none-win_amd64.whl (23.2 MB)
     ---------------------------------------- 1.5/1.5 MB 18.9 MB/s eta 0:00:00
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
     ---------------------------------------- 1.7/1.7 MB 21.5 MB/s eta 0:00:00
     ---------------------------------------- 3.7/3.7 MB 17.0 MB/s eta 0:00:00
  Using cached absl_py-1.4.0-py3-none-any.whl (126 kB)
     ------------------------------------- 895.9/895.9 kB 18.8 MB/s eta 0:00:00
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
     -------------------------------------- 439.2/439.2 kB 2.0 MB/s eta 0:00:00
     ------------------------------------- 781.3/781.3 kB 16.4 MB/s eta 0:00:00
  Using cached tensorboard_d

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD, Adam

# Define the neural network model using stochastic gradient descent
model_sgd = Sequential([
    Dense(64, activation='relu', input_shape=(13,)),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')
])
model_sgd.compile(optimizer=SGD(learning_rate=0.01), loss='binary_crossentropy', metrics=['accuracy'])

# Train the model using stochastic gradient descent
model_sgd.fit(X_train, y_train, epochs=50, batch_size=16, validation_data=(X_test, y_test))

# Define the neural network model using Adam gradient descent
model_adam = Sequential([
    Dense(64, activation='relu', input_shape=(13,)),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')
])
model_adam.compile(optimizer=Adam(learning_rate=0.01), loss='binary_crossentropy', metrics=['accuracy'])

# Train the model using Adam gradient descent
model_adam.fit(X_train, y_train, epochs=50, batch_size=16, validation_data=(X_test, y_test))


Epoch 1/50
52/52 [==============================] - 1s 8ms/step - loss: 8.2016 - accuracy: 0.4927 - val_loss: 0.6936 - val_accuracy: 0.4976
Epoch 2/50
52/52 [==============================] - 0s 4ms/step - loss: 0.6931 - accuracy: 0.5146 - val_loss: 0.6856 - val_accuracy: 0.5024
Epoch 3/50
52/52 [==============================] - 0s 3ms/step - loss: 0.6919 - accuracy: 0.5159 - val_loss: 0.6862 - val_accuracy: 0.5024
Epoch 4/50
52/52 [==============================] - 0s 3ms/step - loss: 0.6907 - accuracy: 0.5159 - val_loss: 0.6823 - val_accuracy: 0.5024
Epoch 5/50
52/52 [==============================] - 0s 3ms/step - loss: 0.6783 - accuracy: 0.5159 - val_loss: 1.0016 - val_accuracy: 0.5024
Epoch 6/50
52/52 [==============================] - 0s 3ms/step - loss: 0.6739 - accuracy: 0.6183 - val_loss: 0.6824 - val_accuracy: 0.5415
Epoch 7/50
52/52 [==============================] - 0s 3ms/step - loss: 0.6755 - accuracy: 0.5817 - val_loss: 0.6769 - val_accuracy: 0.5512
Epoch 8/50
52/52 [==

In [15]:
# Evaluate the neural network models on the testing data
score_sgd = model_sgd.evaluate(X_test, y_test)
score_adam = model_adam.evaluate(X_test, y_test)

print('Stochastic Gradient Descent:',score_sgd)
print('Adam optimizer:',score_adam)


7/7 [==============================] - 0s 3ms/step - loss: 0.4490 - accuracy: 0.8000
Stochastic Gradient Descent: [0.7151213884353638, 0.6634146571159363]
Adam optimizer: [0.44895049929618835, 0.800000011920929]


On the heart disease dataset we have applied Stochastic Gradient Descent and Adam Gradient
Descent to build the multi-layer Neural Network and note down the model accuracy for each.
We can see from the above evaluation that the Adam model performs better than the SGD with an accuracy of 0.8.

As we can see, the SVM linear kernels perform similarly as ANN with adam optimizer, with an accuracy of 0.8